### ISSUE TITLE
运行你的demo，测试是没问题的，为什么把项目引入到自己的项目，就不起作用了

### ISSUE THREAD

**Issue by TOPWARNING** [Coolerfall/Android-AppDaemon#10]
运行你的demo，测试是没问题的，为什么把项目引入到自己的项目，就不起作用了

**Comment by coolerfall** [comment]
怎么引入的，还有是否开启了daemon？

**Comment by TOPWARNING** [comment]
配置方式和demo是一样的，不过我自己项目本身有其他的进程（信鸽推送的），您说的开启daemon是说开启service吗，开启了的
![image](https://cloud.githubusercontent.com/assets/6268829/13244740/8d3890c2-da43-11e5-9fb5-c5325ebb89a5.png)
![image](https://cloud.githubusercontent.com/assets/6268829/13244743/a03301b2-da43-11e5-9561-5616ed0f710b.png)

**Comment by TOPWARNING** [comment]
引入方式是gradle，创建一个daemonService类，配置方式就是上面贴的图，进入应用后开启他，还需要其他什么特殊处理？

**Comment by coolerfall** [comment]
在adb shell里面输入ps | grep <你的包名>查看

**Comment by TOPWARNING** [comment]
使用命令行查看，清理后貌似是把进程清掉了的，清理的过程是
before
![image](https://cloud.githubusercontent.com/assets/6268829/13245068/74234c42-da45-11e5-9632-49845b205750.png)
after
![image](https://cloud.githubusercontent.com/assets/6268829/13245076/8347358a-da45-11e5-9cd4-b9863eb12b7e.png)

**Comment by ZheMingZi** [comment]
为什么demo可以的呢，真是纠结，搞了一天了，求大神指点

**Comment by coolerfall** [comment]
![image](https://cloud.githubusercontent.com/assets/4580284/13245139/1a657396-da46-11e5-9fde-a26d027a6c0b.png)
daemon不是活的好好的么

**Comment by ZheMingZi** [comment]
可是daemon不是死掉了吗，进程列表已经没有它了（苦瓜脸）
![image](https://cloud.githubusercontent.com/assets/6268829/13245174/63a7ed9a-da46-11e5-84f4-edea326db1be.png)

**Comment by coolerfall** [comment]
只要daemon进程还在，就可以把service启动起来，你似乎还没搞明白原理

**Comment by ZheMingZi** [comment]
确实。。这方面完全白痴，那我要在哪里去启动service呢，还是会自动帮我启动

**Comment by coolerfall** [comment]
我这篇博客讲的很清楚了http://coolerfall.com/android/android-app-daemon

**Comment by TOPWARNING** [comment]
![image](https://cloud.githubusercontent.com/assets/6268829/13245994/cc9a22c8-da4b-11e5-86b5-f553930cca69.png)
请问这个packagenamehe和servicename从哪传进来的

**Comment by TOPWARNING** [comment]
![image](https://cloud.githubusercontent.com/assets/6268829/13246255/6a4be3d4-da4d-11e5-9f10-dcd4eb9f2a69.png)
packagenamehe和servicename是从这里传值的吗，也就是它会自动启动我定义的那个service的，可是等了半天，service依然没有重启，囧啊

**Comment by coolerfall** [comment]
按理只要daemon进程没死，就可以把服务启动起来的

**Comment by ZheMingZi** [comment]
![image](https://cloud.githubusercontent.com/assets/6268829/13274533/d7b1b220-dae6-11e5-8f55-0e0e6ed2a569.png)
请问daemon.c文件里的这些日志，在studio logcat里能看到吗

**Comment by ZheMingZi** [comment]
刚才没看到，日志可以看得到，daemon进程一直在跑，service就是起不来，奇怪了
![Uploading image.png…]()

**Comment by ZheMingZi** [comment]
02-24 11:08:02.022 8970-8970/? D/Daemon: check the service once, interval: 120
02-24 11:08:02.022 21220-21220/? D/Daemon: service: com.itcalf.renhe/com.itcalf.renhe.service.RenheService
02-24 11:09:41.682 3420-3451/? E/CoreDaemon: Start Daemon in coredaemon
02-24 11:10:02.892 8970-8970/? D/Daemon: check the service once, interval: 120
02-24 11:10:02.892 22126-22126/? D/Daemon: service: com.itcalf.renhe/com.itcalf.renhe.service.RenheService
02-24 11:12:03.992 8970-8970/? D/Daemon: check the service once, interval: 120
02-24 11:12:03.992 22899-22899/? D/Daemon: service: com.itcalf.renhe/com.itcalf.renhe.service.RenheService
02-24 11:12:41.662 3420-3451/? E/CoreDaemon: Start Daemon in coredaemon
02-24 11:14:05.102 8970-8970/? D/Daemon: check the service once, interval: 120
02-24 11:14:05.102 23930-23930/? D/Daemon: service: com.itcalf.renhe/com.itcalf.renhe.service.RenheService

**Comment by ZheMingZi** [comment]
这是启动应用后打印的日志，您看下有没有什么问题呢
02-24 11:18:03.512 25708-25708/? D/Daemon: package name: com.itcalf.renhe
02-24 11:18:03.512 25708-25708/? D/Daemon: service name: com.itcalf.renhe.service.RenheService
02-24 11:18:03.512 25708-25708/? D/Daemon: interval: 60
02-24 11:18:03.562 25710-25710/? D/Daemon: total num 2
02-24 11:18:03.562 8970-8970/? D/Daemon: handle signal: 15 
02-24 11:18:03.562 8970-8970/? D/Daemon: check the service once, interval: 120
02-24 11:18:03.562 25710-25710/? D/Daemon: kill daemon process success: 8970
02-24 11:18:03.562 25710-25710/? D/Daemon: child process fork ok, daemon start: 25710
02-24 11:18:03.562 25712-25712/? D/Daemon: service: com.itcalf.renhe/com.itcalf.renhe.service.RenheService
02-24 11:18:04.752 25805-25805/? D/Daemon: package name: com.itcalf.renhe
02-24 11:18:04.752 25805-25805/? D/Daemon: service name: com.itcalf.renhe.service.RenheService
02-24 11:18:04.752 25805-25805/? D/Daemon: interval: 60
02-24 11:18:04.792 25810-25810/? D/Daemon: total num 2
02-24 11:18:04.792 25810-25810/? D/Daemon: kill daemon process success: 25710
02-24 11:18:04.792 25710-25710/? D/Daemon: handle signal: 15 
02-24 11:18:04.792 25710-25710/? D/Daemon: check the service once, interval: 120
02-24 11:18:04.792 25810-25810/? D/Daemon: child process fork ok, daemon start: 25810
02-24 11:18:04.792 25811-25811/? D/Daemon: service: com.itcalf.renhe/com.itcalf.renhe.service.RenheService
02-24 11:18:13.692 26020-26020/? D/Daemon: package name: com.itcalf.renhe
02-24 11:18:13.692 26020-26020/? D/Daemon: service name: com.itcalf.renhe.service.RenheService
02-24 11:18:13.692 26020-26020/? D/Daemon: interval: 60
02-24 11:18:13.752 26022-26022/? D/Daemon: total num 2
02-24 11:18:13.752 25810-25810/? D/Daemon: handle signal: 15 
02-24 11:18:13.752 25810-25810/? D/Daemon: check the service once, interval: 120
02-24 11:18:13.762 26022-26022/? D/Daemon: kill daemon process success: 25810
02-24 11:18:13.762 26022-26022/? D/Daemon: child process fork ok, daemon start: 26022
02-24 11:18:13.762 26023-26023/? D/Daemon: service: com.itcalf.renhe/com.itcalf.renhe.service.RenheService

**Comment by coolerfall** [comment]
这不是正常运行的么
