### ISSUE TITLE
间隔时间不起作用

### ISSUE THREAD

**Issue by jackywyz** [Coolerfall/Android-AppDaemon#12]
Daemon.run(this, xx.class, Daemon.INTERVAL_ONE_MINUTE *1);
过了一分钟，进程并没有重启。

**Comment by coolerfall** [comment]
这里的interval不是很精确，由于是fork出来的进程，所以会有一些偏差

**Comment by faith-hb** [comment]
进程干掉后，并没有重新起来啊，vivo xshot机型

**Comment by coolerfall** [comment]
5.x以上不可用

**Comment by faith-hb** [comment]
我是4.3的

**Comment by coolerfall** [comment]
还有就是vivo对native进程做了限制的

**Comment by faith-hb** [comment]
那有没有其他办法保活？

**Comment by coolerfall** [comment]
请参考博客上的友链
