### ISSUE TITLE
arm64-v8a 编译不了

### ISSUE THREAD

**Issue by liushengyi** [Coolerfall/Android-AppDaemon#14]
编译arm64-v8a，报错，求解
 __system_property_get 找不到引用

**Comment by coolerfall** [comment]
新版本的ndk应该是去掉了这些方法了

**Comment by liushengyi** [comment]
那如何解决那？

**Comment by coolerfall** [comment]
你可以不编译arm64版本，本来这个也不涉及到很高的浮点运算，没必要编译arm64的。还有就是可以google一下__system_property_get arm64，有相关的解决方案。

**Comment by liushengyi** [comment]
谢谢。 我项目中有其他依赖需要编译arm64版本。好的，我自己搜搜

**Comment by coolerfall** [comment]
这个编译出来是二进制可执行文件，并不是so库，与你项目中的其他依赖没什么关系的。
