### ISSUE TITLE
编译的daemon没有.so后缀

### ISSUE THREAD

**Issue by congmf** [Coolerfall/Android-AppDaemon#16]
为什么在assets中的编译文件会缺少.so后缀

**Comment by coolerfall** [comment]
编译出来的是二进制可执行文件，不是so库

**Comment by congmf** [comment]
请教一下，那如果要把这个项目在eclipse中使用，该怎么去使用这个二进制文件

**Comment by coolerfall** [comment]
参见项目目录

**Comment by congmf** [comment]
![111](https://cloud.githubusercontent.com/assets/6779694/20202592/3fc7e8c0-a7fb-11e6-944d-5e30cbfdbd67.png)可是加进去后老是报这样的错误

**Comment by coolerfall** [comment]
assets里面的东西没放对吧
