### ISSUE TITLE
华为荣耀6上不起作用

### ISSUE THREAD

**Issue by jtyang** [Coolerfall/Android-AppDaemon#2]
你好，我用华为荣耀6测试，发现service不会被重启，不知道像个推这种推送sdk是怎么实现定时启动的。

**Comment by jtyang** [comment]
另外请问下asstets目录的daemon文件是怎么来的呢？

**Comment by coolerfall** [comment]
有的手机确实是因为系统原因，底层不支持，现目前我遇到小米是这样的。daemon是jni编译出来的。

**Comment by yq800822ss** [comment]
你好，我用了华为的p6测试可以重启但是发现非常耗电 另外实验了华为的几款手机也可以重启但是没发现耗电的情况 不知道能否一份daemon的源码学习学习

**Comment by coolerfall** [comment]
可以的，源码还在整理，过几天会提交上来

**Comment by yq800822ss** [comment]
好的谢谢

**Comment by coolerfall** [comment]
The source code of daemon has released.

**Comment by yq800822ss** [comment]
好的 谢谢

**Comment by yq800822ss** [comment]
之前的daemon 的文件用ida打开感觉是加了壳的 能说下是怎么做到的吗

**Comment by coolerfall** [comment]
没有加壳，正常编译的

**Comment by qujinfeng** [comment]
荣耀6发热发烫，我也在看看，难道问题出在if (version >= 17 || version == 0)
        {
            int ret = execlp("am", "am", "startservice",
                        "--user", "0", "-n", s_name, (char *) NULL);
            LOGD(LOG_TAG, "result %d", ret);
        }
        else
        {
            execlp("am", "am", "startservice", "-n", s_name, (char *) NULL);
        }

```
    LOGD(LOG_TAG , "exit start-service child process");
    exit(EXIT_SUCCESS);
```

请作者关注一下。sleep 还是少用，资源消耗比较大。

**Comment by coolerfall** [comment]
和这段代码没关系，这无非是在启动一个服务而已。

**Comment by qujinfeng** [comment]
作者在分析吗？我今晚下午调试一下，作者有其他的联系方式吗？最近我们客户端存在这个问题。谢谢

**Comment by qujinfeng** [comment]
syscall 接口  难道跟僵尸进程那些系统接口有关系？SYSV  and posix 标准兼容性

**Comment by coolerfall** [comment]
博客上有联系方式 Android developer, Gopher, Open Source, Charcoal Drawing 在2015年04月15日 11:49 ，qujinfeng写道： 作者在分析吗？我今晚下午调试一下，作者有其他的联系方式吗？最近我们客户端存在这个问题。谢谢 — Reply to this email directly or view it on GitHub.

**Comment by qujinfeng** [comment]
thanks,最好有IM 通讯方式

**Comment by qujinfeng** [comment]
作者针对荣耀6发热发烫，现在有什么结果没有？我们公司有资源
