### ISSUE TITLE
Not work on android5.0 and above

### ISSUE THREAD

**Issue by greenvesture** [Coolerfall/Android-AppDaemon#4]
Not work on android5.0 and above, it seems that the daemon process will be killed by system at the same time

**Comment by coolerfall** [comment]
I have tested on Nexus 5, it indeed cannot work on android 5.0 and above.

**Comment by greenvesture** [comment]
Some apps have resolved this problem, such as CM Security. I'm sure they are also using daemon process, but i have not found out the key point. If anyone find it, please share with others here.

**Comment by xiaozhicheng** [comment]
It is still be killed at  MIUI OS

**Comment by zhx00100** [comment]
5.0+上有什么好方案吗?

**Comment by coolerfall** [comment]
没有

**Comment by zhx00100** [comment]
好像市面上的app对android5.0+都无能为力了? 现在还没有什么思路吗~~~~

**Comment by coolerfall** [comment]
已经没有对5.x的进行研究了

**Comment by zhx00100** [comment]
:(  太遗憾了.

**Comment by tbfly** [comment]
It seems Android 5.0+ kill process group make this method don't work. While the create of a D/Z state for a process is a bit hard.

**Comment by coolerfall** [comment]
It seems to be. But I have set setsid() and chdir("/"), then the child process should not be in the same process group with parent process.

**Comment by coolerfall** [comment]
see [MarsDaemon](https://github.com/Marswin/MarsDaemon)
