### ISSUE TITLE
How to stop the service?

### ISSUE THREAD

**Issue by huangbaohuacn** [Coolerfall/Android-AppDaemon#6]
Hey man,I want to stop the service,but it doesn't work,the service is still running.

**Comment by coolerfall** [comment]
You can kill it in adb shell.

**Comment by actionbar** [comment]
thanks very much

**Comment by actionbar** [comment]
And it looks like it's the same.@huangbaohuacn

**Comment by huangbaohuacn** [comment]
use Chinese...@actionbar
