### ISSUE TITLE
华为荣耀6 唤醒不了手机还会发烫，coolerfall请试一试

### ISSUE THREAD

**Issue by shellquery** [Coolerfall/Android-AppDaemon#7]
am startservice之后启动了app_process进程就卡在那里，应该是死循环了，手机发热，目前就这款机器有问题，android4.4.2

**Comment by coolerfall** [comment]
之前有人提到过，确实这款机子有问题，没找到原因

**Comment by shellquery** [comment]
@Coolerfall  你是否知道还有哪些其它机型也有这种问题，我要设置一个机型黑名单

**Comment by coolerfall** [comment]
不知道，请自行测试
